version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=Xeneta_API
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.7"